baseURL = 'https://calebmohamed.com/'
languageCode = 'en-uk'
title = 'caleb mohamed'
publishDir = "../dist"
enableGitInfo = true

[taxonomies]
  themes = "poems/themes"
  series = "poems/series"

[params]
  copyright = '2025'
  datelayout = 'Mon, 02 Jan 2006'
  mainfeedlimit = 20
  [params.author]
    email = 'calebnoahmohamed@gmail.com'
    name = 'Caleb Mohamed'

[permalinks]
  blogs = '/blogs/:year/:slug/'

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[outputFormats]
  [outputFormats.rss]
  basename = 'rss'
  path = 'feeds'
