baseURL = 'https://calebmohamed.com/'
languageCode = 'en-uk'
title = 'caleb-mohamed'
publishDir = "../dist"

[params]
  copyright = '2025'
  blogkey = 'blogstyle'
  csskey = 'jump-up'
  datelayout = 'Mon, 02 Jan 2006'
  [params.author]
    email = 'calebnoahmohamed@gmail.com'
    name = 'Caleb Mohamed'

[permalinks]
  blogs = '/blogs/:year/:slug/'

[outputs]
  home = ['rss']
  section = ['html', 'rss']
  taxonomy = []
  term = []

[outputFormats]
  [outputFormats.rss]
  basename = 'rss'
  path = 'feeds'

[services]
  [servies.rss]
    limit = 15
